= JSilhouette
:linkattrs:
:project-owner:   kordamp
:project-repo:    maven
:project-name:    jsilhouette
:project-group:   org.kordamp.jsilhouette
:project-version: 0.4.0

image:https://github.com/{project-owner}/{project-name}/workflows/Build/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]
image:https://img.shields.io/maven-central/v/{project-group}/{project-name}-core.svg?label=maven[link="https://search.maven.org/#search|ga|1|{project-group}"]

---

JSilhouette provides additional shapes for Java applications. Currently JavaFX is supported.

== Installing

You can get the latest version of **JSilhouette** directly from link:https://bintray.com[Bintray's JCenter] repository or Maven Central.

[source,groovy]
[subs="attributes"]
.gradle
----
repositories {
    jcenter()
}

dependencies {
    compile '{project-group}:jsilhouette-javafx:{project-version}'
}
----

[source,xml]
[subs="attributes,verbatim"]
.maven
----
<dependencies>
    <dependency>
        <groupId>{project-group}</groupId>
        <artifactId>jsilhouette-javafx</artifactId>
        <version>{project-version}</version>
    </dependency>
</dependencies>
----

Refer to the link:http://{project-owner}.github.io/jsilhouette/[guide, window="_blank"] for further information on configuration
and usage.

== Building

You must meet the following requirements:

 * JDK11 as a minimum
 * Gradle 6

You may use the included gradle wrapper script if you don't have `gradle` installed.

=== Installing Gradle

.Manual

 . Download Gradle from http://gradle.org/downloads
 . Unzip the file into a directory without spaces (recommended).
 . Create a GRADLE_HOME environment variable that points to this directory.
 . Adjust your PATH environment variable to include $GRADLE_HOME/bin (%GRADLE_HOME%\bin on Windows).
 . Test your setup by invoking `gradle --version`.

.SDKMAN

 . Follow the instructions found at http://sdkman.io/ to install SDKMAN.
 . You need a POSIX environment if running Windows. We recommend using Babun Shell (http://babun.github.io/)
 . Once SDKMAN is installed invoke `sdk install gradle 6.0`.
 . Test your setup by invoking `gradle --version`.

.Gum

Gum is a wrapper script that facilitates invoking gradle tasks anywhere within a Gradle project. It's smart enough
to use the gradle wrapper if available or your global gradle command. This is an optional download.

 . Follow the instructions found at https://github.com/kordamp/gm to install gum

=== Next Steps

Make a full build issuing `gm build`.

=== Contributing

If you are interested in fixing issues and contributing directly to the code base, please contact us!

=== License

link:LICENSE[LICENSE]

